language: python

# you can use Python 3.7 instead
python: "3.7"

# don't clone more than necessary
git:
  depth: 1

# Install any dependencies
install:
  - pip install -r requirements.txt

before_script:
   - echo "DEBUG = False" >> .env
   - echo "SECRET_KEY = $ SECRET_KEY" >> .env

# script to run tests. Script can have many commands, one per line.
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)
